spring.application.name=novel-outliner
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Database URL (replace 'your_db_name' with your actual database name)
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=mram
spring.datasource.password=SupPass534

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

